bissap_user_user:
    resource: "@BISSAPUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

fos_user_security:
   resource: routing/security.yml
   prefix: /

fos_user_profile:
   resource: routing/profile.yml
   prefix: /compte

fos_user_register:
   resource: routing/registration.yml
   prefix: /inscription

fos_user_resetting:
   resource: routing/resetting.yml
   prefix: /reseting

fos_user_change_password:
   resource: routing/change_password.yml
   prefix: /changement_motdepass
