# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        default_provider:
            entity: { class: BISSAP\UserBundle\Entity\User }
        in_memory:
            memory: 
                users:
                    user:  { password: testmp, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        webservice:
            id: app.webservice_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        orga:
            pattern: ^/orga.*
            anonymous: ~
            form_login:
                provider:        fos_userbundle
                csrf_provider:        form.csrf_provider
                login_path:           fos_orga_security_login
                check_path:           fos_orga_security_check
                default_target_path:  /orga/index
                always_use_default_target_path: true
            logout:
                path:   fos_orga_security_logout
                target: /orga/index

        main:
            pattern: ^/
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                login_path:             fos_user_security_login 
                check_path:             fos_user_security_check
                csrf_provider:          form.csrf_provider
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                default_target_path: /index
                always_use_default_target_path: true
            anonymous:       true            # On autorise les utilisateurs anonymes (non identifiés)
            logout:
                path: fos_user_security_logout
                target: /index
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                failure_path:      /login
                default_target_path: /index
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        BISSAP\UserBundle\Entity\User: sha512
        BISSAP\UserBundle\Security\User\WebserviceUser: bcrypt

    access_control:

     # Liste des page accessibles aux utilisateurs
      - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/orga/connexionOrga$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/orga, role: ROLE_ORGA }