<?php

namespace BISSAP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementsRepository extends EntityRepository
{
	public function findByRegions($region)
	{
		return $this
		->createQueryBuilder('departements')
		->join('departements.regions', 'regions')
		->andWhere('regions.id = :region')
		->setParameter('region', $region)
		->getQuery()
		->getResult();
	}
}
