<?php

namespace BISSAP\CoreBundle\Entity;

/**
 * GenreEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
