<?php

namespace BISSAP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionsRepository extends EntityRepository
{
}
