<?php

namespace BISSAP\CoreBundle\Entity;

/**
 * TypeEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
