<?php

namespace BISSAP\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findUserEventOrgaQuery($type, $genre, $dep)
	{
			$qb = $queryBuilder = $this->_em->createQueryBuilder();

			$qb->select ('u');
			$qb->from($this->_entityName, 'u');
			if( $type != 'Tous' )
			{
				$qb->leftJoin('u.typeE','te');
				$qb->where('te.type = :typeEvent');
				$qb->setParameter("typeEvent", $type);
			}
			if( $genre != 'Tous' )
			{
				$qb->leftJoin('u.genreE','tg');
				if ( $type == 'Tous'){
					$qb->where('tg.genre = :genreEvent');
				}else {
					$qb->andWhere('tg.genre = :genreEvent');
				}
				$qb->setParameter("genreEvent", $genre);
			}
			if ( $dep !='Tous' )
			{
				$qb->leftJoin('u.mobilities', 'mob');
				$qb->leftJoin('mob.departement', 'dep');
				if ( $type == 'Tous' and $genre == 'Tous'){
					$qb->where('dep.num = :idDep');
				}else {
					$qb->andWhere('dep.num = :idDep');
				}
				$qb->setParameter("idDep", $dep);
			}

			return $qb->getQuery()->getResult();

	}
}
